on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-deph: 0
      - uses: actions/setup-node@v2
        with:
          node-version: "18.10.0"
      - name: install dependencies
        run: npm install
      - name: test
        run: npm run test:init